### ISSUE TITLE
Strange output of tests

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#33]
I haven't looked inside the tests yet, but I got a very strange output from them.
```
2) testScenario[lossWithInitialMineHit](ScenarioTest)
java.lang.AssertionError: Minesweeper did not produce the expected output on Line 1
Expected: "┌───┬───┬───┐"
     but: was "┌───┬───┬───┐"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at ScenarioTest.lambda$testScenario$0(ScenarioTest.java:217)
	at ScenarioTest.iterateSimultaneously(ScenarioTest.java:190)
	at ScenarioTest.testScenario(ScenarioTest.java:215)
3) testScenario[winWithInitialMineAvoided](ScenarioTest)
java.lang.AssertionError: Minesweeper did not produce the expected output on Line 1
Expected: "┌───┬───┬───┐"
     but: was "┌───┬───┬───┐"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at ScenarioTest.lambda$testScenario$0(ScenarioTest.java:217)
	at ScenarioTest.iterateSimultaneously(ScenarioTest.java:190)
	at ScenarioTest.testScenario(ScenarioTest.java:215)
4) testScenario[lostGame](ScenarioTest)
java.lang.AssertionError: Minesweeper did not produce the expected output on Line 1
Expected: "┌───┬───┬───┬───┐"
     but: was "┌───┬───┬───┬───┐"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at ScenarioTest.lambda$testScenario$0(ScenarioTest.java:217)
	at ScenarioTest.iterateSimultaneously(ScenarioTest.java:190)
	at ScenarioTest.testScenario(ScenarioTest.java:215)
```

As you can see, expected and the actual output are exactly the same, but the tests fail.

**Comment by alessiogambi** [comment]
It looks weird but there might be a simple explanation for that: two characters that are rendered the same but are indeed different. For example, if you terminate lines with `\r\n` instead of `\n`. You will not see a difference in the message, but the test will (correctly) fail.

**Comment by alessiogambi** [comment]
I tried to run your code on my laptop (Mac) and all the tests pass...

**Comment by alessiogambi** [comment]
Running locally your lastest commit shows a different message:

```
2) testScenario[lossWithInitialMineHit](ScenarioTest)
java.lang.AssertionError: Minesweeper did not produce the expected output on Line 1
Expected: "┌───┬───┬───┐"
     but: was "┌───┬───┬───┐"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at ScenarioTest.lambda$testScenario$0(ScenarioTest.java:217)
	at ScenarioTest.iterateSimultaneously(ScenarioTest.java:190)
	at ScenarioTest.testScenario(ScenarioTest.java:215)
3) testScenario[winWithInitialMineAvoided](ScenarioTest)
java.lang.AssertionError: Minesweeper did not produce the expected output on Line 1
Expected: "┌───┬───┬───┐"
     but: was "











┌───┬───┬───┐"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at ScenarioTest.lambda$testScenario$0(ScenarioTest.java:217)
	at ScenarioTest.iterateSimultaneously(ScenarioTest.java:190)
	at ScenarioTest.testScenario(ScenarioTest.java:215)
```

**Comment by alessiogambi** [comment]
The problem is the following: You clear the screen after each refresh of the game, this causes a number of empty lines to be printed on stdout and is *not* the expected behavior.

**Comment by alessiogambi** [comment]
I clarify this in the program description. To fix your issue it should be enough to remove the code that clears the screen before plotting the UI.
